spring:
  datasource:
    url: jdbc:mysql://localhost/feutrainer
    username: feutrainer
    password: feutrainer
    driver-class-name: com.mysql.jdbc.Driver

  jpa: 
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

server:
  port: 8080
  jsp-servlet:
    init-parameters:
      widgetset: de.zettsystems.FeuTrainerWidgetSet

vaadin:
  servlet:
    productionMode: true