spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    continueOnError: true
    url: jdbc:mysql://localhost/feu
    username: feutrainer
    password: feutrainer
    driver-class-name: com.mysql.jdbc.Driver    

  jpa: 
    hibernate:
      use-new-id-generator-mappings: true
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false

server:
  port: 8080
  compression:
    enabled: true
  jsp-servlet:
    init-parameters:
      widgetset: de.zettsystems.FeuTrainerWidgetSet

vaadin:
  servlet:
    productionMode: false